### ISSUE TITLE
Performance issue while using GCS on Spark  

### ISSUE THREAD

**Issue by BenMizrahiPlarium** [GoogleCloudDataproc/hadoop-connectors#401]
We're trying to process **small** amount of data reading and writing from GCS using Spark.

Connector version: gcs-connector-hadoop2-1.9.17.jar
Files format : Parquet
Estimated data : 5GB~ 
DataProc config: master + drivers himem-16 * 21 workers.

**Issue:**
While running the spark job and writing the files to GCS, all tasks finish fast but job dose not finish.
After sniffing on GCS target path, we sew that folder named: spark_stage(....) has all the data and partitions and we assume that the connector is "moving" (copy & delete) the data to the destination - but this operations takes huge amount of time comparing to the writer operation.

Spark write time takes about ~15 min, all tasks completed but the job in spark stands and holds (I assume it's because operations runs on the driver so no tasks exists), after around 30-40 min the job completed, we checked all the "Spark" components and it's seems to be efficient in reading and writing. without comparing the solutions but the same job with the same metrics as this job writing to **HDFS** cluster takes ~20 min total 

Any suggestion how to tackle this issue ? or even what to check ?

I can provide more detailed information if needed.
Thanks,

**Comment by medb** [comment]
How many files do you read and write? For 5 GiB data size you should write at most 10 files (500 MiB each), because GCS is better suited for processing large files.

See [this blog post](https://cloud.google.com/blog/products/storage-data-transfer/hdfs-vs-cloud-storage-pros-cons-and-migration-tips) for reference on how to optimize your job for using GCS.
